import { z } from "zod";

// A Transaction is either `expected` — a forecast the user has not yet
// confirmed, generated by a Recurring Schedule — or `received`, money that
// actually changed hands (ADR-0011).
//
// Only `received` rows feed Received Income, Net Savings, the Savings Balance
// and a Category's over-limit flag. `expected` rows feed Forecast Income and a
// Category's *committed* figure only. Every read path must filter on this; a
// missed filter is silent, so the filtering lives in computeAnalysis rather
// than being re-derived by each caller.
export const TRANSACTION_STATUSES = ["expected", "received"] as const;

export type TransactionStatus = (typeof TRANSACTION_STATUSES)[number];

export const TransactionStatusSchema = z.enum(TRANSACTION_STATUSES);
